# Generated by Django 5.0.6 on 2026-05-16 14:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('eyfs_am', 'EYFS Morning Dismissal'), ('eyfs_pm', 'EYFS Afternoon Dismissal'), ('primary_pm', 'Primary Afternoon Dismissal'), ('extra', 'Extra / Ad-hoc Session')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Open — Accepting Check-ins'), ('active', 'Active — Dismissal In Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_start', models.TimeField()),
                ('scheduled_end', models.TimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_peak_time', models.TimeField(blank=True, null=True)),
                ('ai_peak_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pickup_sessions',
                'ordering': ['-date', 'scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending — Submitted but not moving'), ('en_route', 'En Route — Travelling to school'), ('arrived', 'Arrived — At or near school'), ('in_queue', 'In Queue — Waiting for children'), ('called', 'Called — Children walking out'), ('collected', 'Collected ✓'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('queue_position', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('queue_token', models.CharField(db_index=True, max_length=10, unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_lat', models.FloatField(blank=True, null=True)),
                ('checkin_lng', models.FloatField(blank=True, null=True)),
                ('checkin_dist', models.FloatField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('confirm_method', models.CharField(blank=True, choices=[('qr', 'QR Code'), ('pin', 'PIN'), ('manual', 'Manual')], max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('ai_flagged', models.BooleanField(db_index=True, default=False)),
                ('ai_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('ai_flag_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pickups.pickupsession')),
            ],
            options={
                'db_table': 'pickup_requests',
                'ordering': ['queue_position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Request Created'), ('status_changed', 'Status Changed'), ('called', 'Children Called Out'), ('completed', 'Pickup Completed'), ('cancelled', 'Cancelled'), ('ai_flagged', 'AI Risk Flagged'), ('override', 'Manual Override')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pickups.pickuprequest')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pickups.pickupsession')),
            ],
            options={
                'db_table': 'queue_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PickupRequestChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('readied_at', models.DateTimeField(blank=True, null=True)),
                ('was_collected', models.BooleanField(default=False)),
                ('readied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readied_children', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pickups.pickuprequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'pickup_request_children',
                'unique_together': {('request', 'student')},
            },
        ),
    ]
