# Generated by Django 5.0.6 on 2026-05-16 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('approach', 'Approach Zone ~500m — triggers en_route'), ('arrival', 'Arrival Zone ~100m — triggers arrived'), ('queue_area', 'Queue Lane ~30m'), ('restricted', 'Restricted — Staff Only')], max_length=20)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('radius_metres', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('send_notification', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'geofence_zones',
            },
        ),
        migrations.CreateModel(
            name='LocationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_metres', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('distance_to_school', models.FloatField(blank=True, null=True)),
                ('eta_seconds', models.IntegerField(blank=True, null=True)),
                ('inside_geofence', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='location_sn_user_id_b4e22b_idx')],
            },
        ),
    ]
