# Generated by Django 5.0.6 on 2026-05-16 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('nursery', 'Nursery (Age 3–4)'), ('reception', 'Reception (Age 4–5)'), ('year_1', 'Year 1 (Age 5–6)'), ('year_2', 'Year 2 (Age 6–7)'), ('year_3', 'Year 3 (Age 7–8)'), ('year_4', 'Year 4 (Age 8–9)'), ('year_5', 'Year 5 (Age 9–10)'), ('year_6', 'Year 6 (Age 10–11)')], max_length=20, unique=True)),
                ('session_type', models.CharField(choices=[('eyfs', 'EYFS (Early Years Foundation Stage)'), ('primary', 'Primary')], max_length=10)),
                ('display_name', models.CharField(max_length=100)),
                ('pickup_order', models.PositiveSmallIntegerField(default=0)),
                ('colour_hex', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'db_table': 'year_groups',
                'ordering': ['pickup_order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
                ('year_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.yeargroup')),
            ],
            options={
                'verbose_name_plural': 'School Classes',
                'db_table': 'school_classes',
                'ordering': ['year_group__pickup_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('pupil_reference', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/%Y/')),
                ('is_active', models.BooleanField(default=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('safe_word', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.schoolclass')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorisedCollector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Legal Guardian'), ('grandparent', 'Grandparent'), ('sibling_18', 'Sibling (18+)'), ('childminder', 'Childminder'), ('family_friend', 'Authorised Family Friend'), ('other', 'Other — ID Verified')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_collect_alone', models.BooleanField(default=True)),
                ('id_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='can_collect', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='students.student')),
            ],
            options={
                'db_table': 'authorised_collectors',
                'unique_together': {('student', 'user')},
            },
        ),
    ]
